# fluentd global
version: '3'
services:

  fluentd:
    build: ./fluentd
    image: localhost:5000/fluentd:prometheus
    expose:
      - 24231 # prometheus api
    ports:
      - 24224:24224
      - 24224:24224/udp
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf:ro
    restart: always

networks:
  default:
    external:
      name: fluent_shared
