# GitLab CE
version: '3'
services:

  gitlab-ce:
    image: gitlab/gitlab-ce
    expose:
      - 80
    volumes:
      - ./conf:/etc/gitlab
      - ~/docker/.gitlab/logs:/var/log/gitlab
      - ~/docker/.gitlab/data:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.nol0nger.cf'
        mattermost_external_url 'http://mattermost.nol0nger.cf'
        registry_external_url 'http://registry.nol0nger.cf'
    restart: always
