# passbolt
version: '3'
services:

  database:
    image: mariadb
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: passbolt
      MYSQL_DATABASE: passbolt
      MYSQL_USER: passbolt
      MYSQL_PASSWORD: P4ssb0lt

  passbolt:
    image: passbolt/passbolt
    links:
      - database
    ports:
      - 443:443
    networks:
      - default
      - nginx
    environment:
      DB_HOST: database
      VIRTUAL_HOST: passbolt.example.com
      VIRTUAL_PORT: 443
      LETSENCRYPT_HOST: passbolt.example.com
      LETSENCRYPT_EMAIL: admin@passbolt.com

networks:
  nginx:
    external:
      name: nginx_shared
