# Nginx + auto-generate nginx.conf + create certs by let's encrypt
version: '3'
services:

# sample // httpd docker container
  www-root:
    image: httpd:alpine
    expose:
      - 80
   environment:
     VIRTUAL_HOST: example.com
     VIRTUAL_PORT: 80
     LETSENCRYPT_HOST: example.com
     LETSENCRYPT_EMAIL: admin@example.com
