# Nginx + auto-generate nginx.conf + create certs by let's encrypt
version: '3'
services:

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/htpasswd/:/etc/nginx/htpasswd:ro
      - conf_nginx:/etc/nginx/conf.d/:ro
      - conf_vhost:/etc/nginx/vhost.d/:ro
      - conf_certs:/etc/nginx/certs:ro
      - acme_challenge:/usr/share/nginx/html:rw
    labels: # separete-container
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: docker.nginx-proxy.{{.ID}}.access
    restart: always

  nginx-generate:
    image: jwilder/docker-gen
    container_name: nginx-generate
    links:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ~/docker/.htpasswd/:/etc/nginx/htpasswd:ro
      - ./nginx.tmpl:/etc/docker-gen/nginx.tmpl:ro
      - conf_nginx:/etc/nginx/conf.d/:rw
      - conf_certs:/etc/nginx/certs/:ro
    labels: # separete-container
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen
    command: ["-notify-sighup","nginx-proxy","-watch","/etc/docker-gen/nginx.tmpl", "/etc/nginx/conf.d/default.conf"]
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - nginx-proxy
      - nginx-generate
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - conf_certs:/etc/nginx/certs/:rw
      - conf_vhost:/etc/nginx/vhost.d/:rw
      - acme_challenge:/usr/share/nginx/html:rw
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      NGINX_DOCKER_GEN_CONTAINER: nginx-generate
    restart: always

# before compose, "docker network create nginx_shared"
# before compose, "docker network create nginx_shared"
networks:
  default:
    external:
      name: nginx_shared

volumes:
  acme_challenge:
    driver: local
  conf_nginx:
    driver: local
  conf_vhost:
    driver: local
  conf_certs:
    driver: local
