version: '3.1'
services:
  db:
    image: mysql
    volumes:
      - sql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  sql-data:
    driver: local
