version: '3'
services:

  nginx:
    image: nginx:alpine
    links:
      - web
      - elasticsearch
      - kibana
      - portainer
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro

  webclient:
    image: alpine
    links:
      - nginx
    volumes:
      - ./shell/wget.sh:/root/wget.sh:ro
    command: /root/wget.sh
    restart: always

  web:
    image: httpd:alpine
    links:
      - fluentd
    expose:
      - 80
    logging:
      driver: fluentd
        options:
          fluentd-address: localhost:24224
          tag: httpd.access
